/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Presentation.ViewController;

public class App {

    public static void main(String[] args) {
        ViewController controller = new ViewController();
        controller.start();
    }
}